_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 5

progress_bar_refresh_rate: 5
log_every_n_steps: 5
resume_from_checkpoint: null
weights_summary: "full"

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
