# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: base.yaml
  - datamodule: ou.yaml
  - callbacks: none.yaml
  - logger: null # set logger here or use command line (e.g. `python run.py logger=wandb`)

  - mode: default.yaml

  - experiment: null
  - hparams_search: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  # use joblib for multi runs
  - override hydra/launcher: joblib

hydra:
  job:
    env_set:
      TERM: xterm-256color
      HYDRA_FULL_ERROR: "1"
      JAM_PROJ_PATH: /home/qzhang419/projects/hpis
  launcher:
    # override the number of jobs for joblib
    n_jobs: 6
# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# check performance on test set, using the best model achieved during training
# lightning chooses best model based on metric specified in checkpoint callback
test_after_training: false

# seed for random number generators in pytorch, numpy and python.random
seed: null

# name of the run is accessed by loggers
# should be used along with experiment mode
name: null

# auto select gpu with lowest util rate
agpu: false
